### ISSUE TITLE
Cancelable vs Cancellable?

### ISSUE THREAD

**Issue by andywhite37** [reazen/relude-reason-react#1]
I went with the double `l`, but not sure which is preferable.

**Comment by mlms13** [comment]
This suggests that one `l` is more American English and two is more everybody else: https://grammarist.com/spelling/cancel/

:us: USA! USA! :us: 

But also, I really don't care. :)

**Comment by andywhite37** [comment]
Yeah, my heart really wants `cacencellation`/`cancellable`/`canceller`, but `canceler` seems to be the "American" way.  It just looks wrong though :smile:

**Comment by mlms13** [comment]
Just realize that if you choose `cancellable`, that means we'll have to name our future color library `relude-colour` and ask yourself if that's a world you want to live in.

**Comment by andywhite37** [comment]
That's a good point.  We must implement #brexit

**Comment by andywhite37** [comment]
Ok, everything is single `l` now.  :us:
