### ISSUE TITLE
Should the render functions be significant data first or last?

### ISSUE THREAD

**Issue by andywhite37** [reazen/relude-reason-react#11]
The render helper functions currently take the React elements first and significant data last, but it might actually make sense to take the sig data first.  We'll have to try it out more in the wild and figure out what we're more likely to want to partially apply - the elements or the data.

**Comment by andywhite37** [comment]
The argument for sig data first would be for use cases like this:

```reason
// sig data first
let ifVisible = ReludeReact.Render.ifTrue(state.isVisible);
let ifBusy = ReludeReact.Render.asyncResultIfBusy(state.result);

<div>
  {ifVisible(<Foo />)}
  {ifBusy(<Bar />)}
</div>
```

This can be achieved with sig data last too, but it's a little more awkward

```reason
// sig data last
let ifVisible = ReludeReact.Render.ifTrue(_, state.isVisible);
let ifBusy = ReludeReact.Render.asyncResultIfBusy(_, state.result);

<div>
  {ifVisible(<Foo />)}
  {ifBusy(<Bar />)}
</div>
```

**Comment by mlms13** [comment]
Originally I had thought (specifically in the case of the boolean-based `ifTrue` function) that the React element felt like the most significant data, and that partially applying a single boolean might be a common use case. But that could be achieved by:

```reason
let ifVisible = ReludeReact.Render.ifTrue(_, state.isVisible);
<div>
  {ifVisible(<Foo />)}
  {ifVisible(<Bar />)}
</div>
```

And for all the other functions (option, result, async), it seems like the most common approach would be to pipe that data in (like you did [here](https://github.com/reazen/relude-reason-react/blob/master/examples/demo/AnimalListView.re#L77-L82)). I could even see piping a `bool` value being useful, e.g.:

```reason
state.selectedValues
|> List.isEmpty
|> ReludeReact.Render.ifTrue(<WarningAlert message="Pick at least one thing" />)
```

**Comment by andywhite37** [comment]
Good points.  I'll leave it alone for now, but we can change it in the future

**Comment by andywhite37** [comment]
I'm going to close this now - we can revisit later if needed.
