### ISSUE TITLE
Order of reducer arguments

### ISSUE THREAD

**Issue by mlms13** [reazen/relude-reason-react#12]
One thing I like about the hooks `useReducer` is that the signature looks like `('state, 'action) => 'state`, where `'state` is the first argument. This allows you to do, e.g.:

```reason
let (state, dispatch) = React.userReducer(state =>
  fun
  | Increment => {count: state.count + 1}
  | Decrement => {count: state.count - 1}
  | Reset => {count: 0},
  { count: 0 }
);
```

Basically, this order of arguments is helpful for matching on actions, and it's (more) consistent with the signature of `foldLeft` used elsewhere. Thoughts on using this order of arguments in `ReludeReact.Reducer.useReducer`, @andywhite37?

**Comment by andywhite37** [comment]
I think that makes sense.  I think I just copied the bloodyowl version (not 100% sure), and didn't think twice about it.  If you want to make that change, it sounds good to me.

Would you mind updating the README if you do change it - I think I just copy and pasted one of the demo files in there, which is maybe a bad idea, but I wanted a sample that was easy to view.

**Comment by mlms13** [comment]
I personally just benefited from the fact that the README had such a complete example in it, so I'll be happy to update that as well.
