### ISSUE TITLE
Functions for constructing `update` values in reducer

### ISSUE THREAD

**Issue by andywhite37** [reazen/relude-reason-react#19]
@mlms13 pointed out that it would be useful to have function versions of the `Update`/`UpdateWithIO`/etc. `update` constructors, to allow for cleaner usage with `|>`.

**Comment by mlms13** [comment]
Glad you opened this, because I forgot what I was wanting to work on right now. :) I'll try to get this in and then make a release (with the changes to Reducer and additions to Effect that are already in master).
